### ISSUE TITLE
.env MONITORING_CONTAINERS=True case sensitive

### ISSUE THREAD

**Issue by EdouardLvdl** [skalenetwork/skale-node#181]
Skale node exporter containers will not start if MONITORING_CONTAINERS is not spelt to "True" as it is case sensitive

For example if you create a .env file with MONITORING_CONTAINERS=TRUE and run "sudo skale node update .env", the node and most containers will start. The node will be active. However exporter containers will not start, resulting in no data sent over watchdog 3009.

┆Issue is synchronized with this [Jira Task](https://skalelabs.atlassian.net/browse/SKALE-3768)

**Comment by alexgex** [comment]
@EdouardLvdl If exporter containers don't start it wouldn't affect watchdog data

**Comment by EdouardLvdl** [comment]
@alexgex sorry for the confusion in the wording

These are the containers that will not start if "True" is misspelt

skale_nginx
redis
celery
config_base_1
monitor_cadvisor 
monitor_node_exporter

**Comment by alexgex** [comment]
@EdouardLvdl yes, you're right - skale_nginx should be anyway started, but it is not. Will be fixed
Thank you for reporting!

**Comment by gannakulikova** [comment]
@EdouardLvdl  Nginx issue has been fixed - thank you very much! Please see the PR reference: https://github.com/skalenetwork/node-cli/pull/393
