### ISSUE TITLE
Sync node: remove CPU and memory limitations

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/skale-node#434]
We shouldn't limit CPU and memory for a sync node to allow different machines and configurations. 

CPU and memory limits should be removed:

- `node-cli`/`skale-node` - from config files and docker-compose (CPU shares, etc) + remove hardware checks
- `skale-admin` - from skaled container runner

**Comment by oleksandrSydorenkoJ** [comment]
related to https://github.com/skalenetwork/internal-support/issues/262
closed as duplicate
