### ISSUE TITLE
add new config parameters `transactionQueueLimitBytes` and `futureTransactionQueueLimitBytes`

### ISSUE THREAD

**Issue by olehnikolaiev** [skalenetwork/skale-node#525]
as these parameters were added to skaled in order to limit transaction queue size and they are configurable we need to add them to config generation procedure
constants to be discussed separately

**Comment by badrogger** [comment]
@olehnikolaiev In which schain config section they are expected?

**Comment by olehnikolaiev** [comment]
@badrogger  ['skaleConfig']['nodeInfo']

**Comment by olehnikolaiev** [comment]
constants were chosen in a such way that in tx queue will not consume more than 1GB in any situation. tx queue consumes RAM not only to store txns themselves but also to store a lot of additional information like txns hashes, senders' addresses and nonces, etc. for small txns we have a limitation of tx queue size in number of txns, for large txns we will have  `transactionQueueLimitBytes` limit. the constants were chosen in assumption that average txn size in the queue is 50kB.

**Comment by DmytroNazarenko** [comment]
skale-node: beta
skaled: 3.17.0-beta.1

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Regression network

skale-node: regression-2.2 (beta)
skaled: 3.17.0-beta.3


```
            "transactionQueueLimitBytes": 69206016,
            "futureTransactionQueueLimitBytes": 140509184,
```
