### ISSUE TITLE
Create patch timestamp for StorageDestructionPatch

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skale-node#527]
Create `storageDestructionPatchTimestamp` for skaled v3.17.0 for enable fast destruction patch
```[tasklist]
### Tasks
- [ ] https://github.com/skalenetwork/skale-node/issues/530
```

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.1
skale-node: beta

**Comment by DmytroNazarenko** [comment]
`storageDestructionPatchTimestamp` is set in skale-node: https://github.com/skalenetwork/skale-node/blob/develop/static_params.yaml#L44, https://github.com/skalenetwork/skale-node/blob/develop/static_params.yaml#L131 etc

It enables contract destruction mechanism in skaled - https://github.com/skalenetwork/skaled/issues/1347
Patch usage: https://github.com/skalenetwork/skaled/pull/1546/files#diff-e0ede0bb332d68b9091234d3d2d4dc1d1166e3d424a003158bd7b47366a01945R513
 
New contract destruction mechanism iterates only over the keys with a given prefix (contract address). Previously it was iterated over the all set of keys in the db, that was time-consuming

**Comment by DmytroNazarenko** [comment]
Added also powCheckPatchTimestamp

**Comment by EvgeniyZZ** [comment]
Required activity: 
- check that skaled read/handle new variable.
- set timestamp UPD: set to 0

**Comment by oleksandrSydorenkoJ** [comment]
@badrogger @DmytroNazarenko 
https://github.com/skalenetwork/skale-node/blob/beta/static_params.yaml - not implemented yet in beta 


skaled 3.17.0-beta.8 works with powCheckPatchTimestamp and storageDestructionPatchTimestamp without any warnings or crashes

```
            "storageDestructionPatchTimestamp": 1689163200,
            "powCheckPatchTimestamp": 1693494000,
```

**Comment by DmytroNazarenko** [comment]
skale-node:develop

**Comment by oleksandrSydorenkoJ** [comment]
Implementeed for develop branch 
https://github.com/skalenetwork/skale-node/commit/0d152736fec5596b2d8981b762a189ace324ddef
https://github.com/skalenetwork/skale-node/blob/develop/static_params.yaml#L44C1-L45C1
