### ISSUE TITLE
update storageDestructionPatchTimestamp and powCheckPatchTimestamp for stable

### ISSUE THREAD

**Issue by olehnikolaiev** [skalenetwork/skale-node#530]

**Comment by oleksandrSydorenkoJ** [comment]
@olehnikolaiev  add more details to the task and versions of skaled with implemented timestamps

**Comment by oleksandrSydorenkoJ** [comment]
https://github.com/skalenetwork/skale-node/blob/develop/static_params.yaml#L44C1-L45C1
