### ISSUE TITLE
Add patch timestamps for 3.18.0 version of skaled

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skale-node#575]
Need to add patch timestamps for 3.18.0 skaled

- [ ] pushZeroPatchTimestamp
- [ ] precompiledPatchTimestamp
- [ ] correctForkInPowPatchTimestamp

**Comment by oleksandrSydorenkoJ** [comment]
verified on 2.3.0-beta.0
https://github.com/skalenetwork/skale-node/blob/e43df50da1944d1d10155454b3e6100d9b0c781a/static_params.yaml#L231C1-L232C1
