### ISSUE TITLE
Filebeat container don't close files which are deleted

### ISSUE THREAD

**Issue by OleksanderSalamatov** [skalenetwork/skale-node#614]
Filebeat container don't close files which are deleted, which leads to high disk space usage, as filesystem still treats them as existing files.

admin: 2.5.3

Before skale_filebeat restart:
`/dev/sdb1                                                  210G   210G  0  100% / `

After skale_filebeat restart:
`/dev/sdb1                                                  210G   52G  147G  27% /`

Part of `sudo lsof +L1` (list of opened files):
```
filebeat  3763267 root  745r   REG   8,17 250000038     0 32427366 /var/lib/docker/containers/2023ada371d2b658288f399228c109f3fb572f2ab307cbe43b002893d6915fe9/2023ada371d2b658288f399228c109f3fb572f2ab307cbe43b002893d6915fe9-json.log.4 (deleted)
filebeat  3763267 root  746r   REG   8,17 250012449     0 32428142 /var/lib/docker/containers/2023ada371d2b658288f399228c109f3fb572f2ab307cbe43b002893d6915fe9/2023ada371d2b658288f399228c109f3fb572f2ab307cbe43b002893d6915fe9-json.log.4 (deleted)
```

Possible solution will be update of filebeat itself

**Comment by alexgex** [comment]
It is not a bug, it is an expected behavior as QA testnet nodes are trying to send logs to ELK servers that drop these logs on Logstash level.  
> In the default behaviour, Filebeat opens the files and keeps them open until it reaches the end of them. In situations when the configured output is blocked (e.g. Elasticsearch or Logstash is unavailable) for a long time, this can cause Filebeat to keep file handlers to files that were deleted from the file system in the mean time. As long as Filebeat keeps the deleted files open, the operating system doesn’t free up the space on disk, which can lead to increase disk utilization or even out of disk situations.
