### ISSUE TITLE
Update offchain infrastructure to Pacifica V3

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skale-node#633]
Need to upgrade all mainnet offchain infrastructure to Pacifica V3 release:

- [x] Update mainnet indexer nodes
- [x] Update mainnet archive nodes
- [x] Update mainnet sync nodes

**Comment by alexgex** [comment]
1. All Indexer nodes are successfully updated to Pacifica V3.
2. All Archive nodes are stopped now and will be (or already are) replaced by Indexer nodes*.
3. All Sync nodes - 3 nodes owned by Exorde - have to be updated by Exorde team.

*Europa and Nebula Archive nodes will be launched again on the corresponding existing instances when a new archive node release is ready.
